# Generated by Django 3.1.7 on 2022-02-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('tel', models.CharField(max_length=12, verbose_name='Tel /Phone')),
                ('address', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=3, verbose_name='Country')),
                ('file_id', models.FileField(upload_to='', verbose_name='ID card file')),
                ('file_face', models.FileField(upload_to='', verbose_name='Face file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
